#!/usr/bin/python3

CONFIGDIR = "/tmp/"

import os
from sys import exit
import configparser

config = configparser.ConfigParser()
config.read(os.path.join(CONFIGDIR,"settings.txt"))

if len(config.sections()) == 0:
    raise RuntimeError("Invalid settings.txt")

for section in config.sections():
    print("# {}".format(section))
    for setting in config[section]:
        value = config[section].get(setting, None)
        if value is not None:
            if value not in ["true", "false"]:
                value = '"{}"'.format(value)
            print("{}_{}={}".format(section.upper(), setting.upper(), value))
